services:
  - name: backend-service
    type: web
    runtime: docker
    repo: https://github.com/xtrajank/strat_tips
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: QUICKBOOKS_CLIENT_ID
        sync: false
      - key: QUICKBOOKS_CLIENT_SECRET
        sync: false
    dockerCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"

  - name: frontend-service
    type: static  # If using Docker, change this to "web"
    repo: https://github.com/xtrajank/strat_tips
    rootDir: src
    buildCommand: "npm install && npm run build"
    publishDirectory: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://strat-tips.onrender.com"